swagger: "2.0"
info:
  version: "1.0.0"
  title: "Order Tracker API"
paths:
  /order/get/{order_uid}:
    get:
      summary: "Get an order by its UID"
      parameters:
        - name: "order_uid"
          in: "path"
          required: true
          type: "string"
      responses:
        "200":
          description: "Successful operation"
          schema:
            $ref: "#/definitions/Order"
          examples:
            application/json:
              {
                "order_uid": "b563feb7b2b84b6test",
                "track_number": "WBILMTESTTRACK",
                "entry": "WBIL",
                "delivery": {
                  "name": "Test Testov",
                  "phone": "+9720000000",
                  "zip": "2639809",
                  "city": "Kiryat Mozkin",
                  "address": "Ploshad Mira 15",
                  "region": "Kraiot",
                  "email": "test@gmail.com"
                },
                "payment": {
                  "transaction": "b563feb7b2b84b6test",
                  "request_id": "",
                  "currency": "USD",
                  "provider": "wbpay",
                  "amount": 1817,
                  "payment_dt": 1637907727,
                  "bank": "alpha",
                  "delivery_cost": 1500,
                  "goods_total": 317,
                  "custom_fee": 0
                },
                "items": [
                  {
                    "chrt_id": 9934930,
                    "track_number": "WBILMTESTTRACK",
                    "price": 453,
                    "rid": "ab4219087a764ae0btest",
                    "name": "Mascaras",
                    "sale": 30,
                    "size": "0",
                    "total_price": 317,
                    "nm_id": 2389212,
                    "brand": "Vivienne Sabo",
                    "status": 202
                  }
                ],
                "locale": "en",
                "internal_signature": "",
                "customer_id": "test",
                "delivery_service": "meest",
                "shardkey": "9",
                "sm_id": 99,
                "date_created": "2021-11-26T06:22:19Z",
                "oof_shard": "1"
              }
        "404":
          description: "Order not found"
definitions:
  Order:
    type: "object"
    properties:
      order_uid:
        type: "string"
      track_number:
        type: "string"
      entry:
        type: "string"
      delivery:
        $ref: "#/definitions/Delivery"
      payment:
        $ref: "#/definitions/Payment"
      items:
        type: "array"
        items:
          $ref: "#/definitions/Item"
      locale:
        type: "string"
      internal_signature:
        type: "string"
      customer_id:
        type: "string"
      delivery_service:
        type: "string"
      shardkey:
        type: "string"
      sm_id:
        type: "integer"
      date_created:
        type: "string"
        format: "date-time"
      oof_shard:
        type: "string"
  Delivery:
    type: "object"
    properties:
      name:
        type: "string"
      phone:
        type: "string"
      zip:
        type: "string"
      city:
        type: "string"
      address:
        type: "string"
      region:
        type: "string"
      email:
        type: "string"
  Payment:
    type: "object"
    properties:
      transaction:
        type: "string"
      request_id:
        type: "string"
      currency:
        type: "string"
      provider:
        type: "string"
      amount:
        type: "number"
      payment_dt:
        type: "integer"
      bank:
        type: "string"
      delivery_cost:
        type: "number"
      goods_total:
        type: "number"
      custom_fee:
        type: "number"
  Item:
    type: "object"
    properties:
      chrt_id:
        type: "integer"
      track_number:
        type: "string"
      price:
        type: "number"
      rid:
        type: "string"
      name:
        type: "string"
      sale:
        type: "integer"
      size:
        type: "string"
      total_price:
        type: "number"
      nm_id:
        type: "integer"
      brand:
        type: "string"
      status:
        type: "integer"
